name: CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "22"
          cache: true

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          vp install

      - name: Setup Mago
        uses: nhedger/setup-mago@v1

      - name: Run Mago
        run: |
          composer format --dry-run
          composer lint --reporting-format=github
          composer analyze --reporting-format=github

      - name: Lint & Format Frontend
        run: vp check

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Security Audit
        run: composer audit --no-interaction

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["8.4", "8.5"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: xdebug

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "22"
          cache: true

      - name: Install Node Dependencies
        run: vp install

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Build Assets
        run: vp build

      - name: Tests
        run: ./vendor/bin/pest
